### ISSUE TITLE
Possibility to set withArchived() as default instead of withoutArchived()

### ISSUE THREAD

**Issue by zaheer15351** [joelbutcher/laravel-archivable#13]
Is there any way of changing the default behaviour of this package where `withoutArchived()` is used as a default scope, to change it to something else that is supported i.e. `withArchived()` ?

**Comment by joelbutcher** [comment]
I would extend the `ArchivableScope` class and modify the `apply` method as you need. You'll then need to create a new trait with the same `bootArchived` method which loads in the new extended scope class:

```php
trait Archivable
{
    public static function bootArchivable()
    {
        self::addGlobalScope(new ExtendedArchivableScope());
    }
}
```

Then in your model do something like this:

```php
namespace App\Models;

use App\Concerns\Archivable;
use LaravelArchivable\Archivable as BaseArchivable;

class Post extend Model
{
    use Archivable, BaseArchivable {
        Archivable::bootArchivable insteadof BaseArchivable;
    }
}
```
