### ISSUE TITLE
Add "addObservableEvents" to initializeArchivable

### ISSUE THREAD

**Issue by Kaylakaze** [joelbutcher/laravel-archivable#21]
So that the events fired by this trait can be handled properly in the model's observer, you need to add the following to the initializeArchivable method:
`$this->addObservableEvents([
            'archiving',
            'archived',
            'unArchiving',
            'unArchived'
        ]);`

**Comment by joelbutcher** [comment]
Thanks for this - will take a look at some point later this week. If you have time yourself, please feel free to submit a PR!

**Comment by joelbutcher** [comment]
Resolved in `v1.3.1`
