### ISSUE TITLE
Archiving doesn't trigger default Eloquent events

### ISSUE THREAD

**Issue by Kaylakaze** [joelbutcher/laravel-archivable#25]
This seems to be because you're using $query->update($columns) instead of $this->update($columns). Why is your runArchive method so... weird when your unArchive method looks as expected?

**Comment by Kaylakaze** [comment]
I've rewritten the archive method in my code to make it like the unArchive method in structure, but since I don't understand why you handled the archive and runArchive methods the way that you did, I don't know if I'm missing something.

**Comment by rvzug** [comment]
You could use the events 
```php
            'archiving',
            'archived',
            'unArchiving',
            'unArchived'
```

when you want to do something while/after archiving/unarchiving, eg. call the update event manually.

**Comment by joelbutcher** [comment]
You're probably calling the wrong method... `runArchive` only handles query / attribute logic (similar to how Laravel themselves do soft deletes). The methods that calls all the events are:
- `archive` (calls `runArchive` to handle query logic)
  - Fires the `archiving` and `archived` model events
- `unArchive`
  - Fires the `unArchiving` and `unArchived` model events

---

> Why is your runArchive method so... weird

This package is basically a carbon copy of what Laravel does for it's `SoftDeletes` eloquent trait with a different database column name, the code is pretty much identical to that trait and behaves in more or less the same way.

As I said above, `runArchive` is the actual logic behind applying the archive timestamp. In that regard, this is the order of processes for that method:

1. Create a new query and apply a `where id = %s` clause
2. Get the current fresh timestamp the model is to be "archived" for
3. Set the attribute values and the query values
4. Set the "updated at" timestamp if it exists on the model
5. Run the query
6. Update this model instances attributes for `archived_at` and `updated_at` (if present) with the new values

**Comment by Kaylakaze** [comment]
> You're probably calling the wrong method... `runArchive` only handles query / attribute logic (similar to how Laravel themselves do soft deletes). The methods that calls all the events are:

I understand that. You missed my point. Calling "archive" does not call the "updated" trigger on an Eloquent model because runArchive uses a QueryBuilder call to make the change to the database/model instead of an Eloquent call. Calling "unArchive" DOES trigger the "updated" event because it uses an Eloquent call to make the database/model update.

I understand what runArchive does. What I didn't understand is why you're using QueryBuilder calls in it instead of Eloquent calls when you use Eloquent calls in the unarchive method. I don't even know why you need "runArchive". This is the "archive" method that I used to override yours.
```
public function archive()
{
        if (!$this->exists) {
            return false;
        }

        if (!is_null($this->{$this->getArchivedAtColumn()})) {
            return true;
        }

        if ($this->fireModelEvent('archiving') === false) {
            return false;
        }

        $this->{$this->getArchivedAtColumn()} = $this->freshTimestamp();

        $result = $this->save();

        $this->fireModelEvent('archived', false);

        return $result;
}
```

Apart from the call to touchOwners (which could easily be added) I don't understand what your archive and runArchive methods do that aren't covered by this method, thus my questions.

**Comment by joelbutcher** [comment]
I'm really not sure I fully understand the problem here. Just listen on the `archived` event for reacting to this action and `updated` for everything else?

**Comment by Kaylakaze** [comment]
Do you not understand that there are dozens of packages that do various things like logging or notifications to other systems that listen for the updated action? If a model is updated, it should be firing the updated trigger. That's the entire point of Laravel.
Even beside that point, the methods you use are needlessly over-complicated for what you're trying to accomplish.

I mean, it doesn't really matter to me because, like I've said, I just wrote an override to handle it. I just wanted to check if there was a good reason it was written the way it was.

**Comment by joelbutcher** [comment]
> That's the entire point of Laravel.

So why do Laravel themselves implement their `SoftDeletes` trait in the exact same manner, hmm? 

> the methods you use are needlessly over-complicated

Again, see my previous comment ;)

> I mean, it doesn't really matter to me

So why continue to comment and argue the same point if it doesn't matter to you? 🧐
