### ISSUE TITLE
Archive Relationship Items

### ISSUE THREAD

**Issue by AElleray** [joelbutcher/laravel-archivable#28]
Hello  do you have a solution for archiving all the items in a relationship

when i archive the parent asset   id like all the child assets to also archive?

Thanks 

Ant

**Comment by joelbutcher** [comment]
There are a number of ways to achieve this. None of them I've included in this package as I didn't want to force a "right way" of doing things. A couple of suggestions to consider:

1. Listening to the `'archived'` model event and applying archives to all children.
2. Keeping the children "unArchived", but using access control / gates to block access if the parent is archived
3. Extending and modifying the logic in the trait to suit your needs
