### ISSUE TITLE
Support Laravel 6 (LTS) and 7

### ISSUE THREAD

**Issue by wilsenhc** [joelbutcher/laravel-archivable#4]
Hello,

I would like to start saying that I like the idea behind this package. I read about it in Laravel-News blog

I tested it on a new Laravel 8 project and it works great, but I would like to add this package to some Laravel 6 & 7 project in production at the moment

**Comment by joelbutcher** [comment]
@wilsenhc Feel free to PR this

**Comment by wilsenhc** [comment]
Working on it using TravisCI for running tests on multiple Laravel versions

**Comment by joelbutcher** [comment]
@wilsenhc is there any particular reason you've gone with TravisCI? And would you have any objection looking into GitHub actions for this instead?

**Comment by wilsenhc** [comment]
No objection at all, it's actually great input (I had forgotten about GitHub Actions)

I'll have a look on how to replicate the same using GitHub Actions

**Comment by joelbutcher** [comment]
@wilsenhc any updates on this?

**Comment by joelbutcher** [comment]
Closing this as I have no plans to implement the support myself
